## Упражнения по библиотеке Numpy

In [20]:
import numpy as np
import timeit
from collections import Counter

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [21]:
arr_t1 = np.random.randint(0, 12, size = 8)
print("Исходный массив", arr_t1)

arr_t1[(arr_t1 > 3) & (arr_t1 < 8)] *= -1
print("Конечный массив", arr_t1)

Исходный массив [ 5  1 10  8  6  7 10 11]
Конечный массив [-5  1 10  8 -6 -7 10 11]


**2.** Заменить максимальный элемент случайного массива на 0

In [22]:
arr_t2 = np.random.randint(-10, 10, size = 10)
print("Исходный массив", arr_t2)

arr_t2[arr_t2.argmax()] = 0
print("Конечный массив", arr_t2)

Исходный массив [-1  6 -4 -1  2  5  9 -2  5 -8]
Конечный массив [-1  6 -4 -1  2  5  0 -2  5 -8]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [23]:
arr_t3 = np.arange(0, 6).reshape(3, 2)
print("Исходный массив:\n", arr_t3)

product = np.array(np.meshgrid(*arr_t3)).T.reshape(-1, arr_t3.shape[0])
print("Прямое произведение массивов:\n", product)

Исходный массив:
 [[0 1]
 [2 3]
 [4 5]]
Прямое произведение массивов:
 [[0 2 4]
 [0 3 4]
 [1 2 4]
 [1 3 4]
 [0 2 5]
 [0 3 5]
 [1 2 5]
 [1 3 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [24]:
arr_a_t4 = np.array([[1, 4, 3], [9, 5, 6], [12, 8, 9], [2, 4, 7], 
                    [12, 9, 8], [0, 6, 9], [1, 12, 9], [8, 5, 9]])
arr_b_t4 = np.array([[8,5], [9,12]])

print("Массив А:")
print(arr_a_t4)
print("\nМассив B:")
print(arr_b_t4)

def contains_elements(a_row: np.array, b_row_1: np.array, b_row_2: np.array) -> bool:
    return np.any(np.isin(a_row, b_row_1)) and np.any(np.isin(a_row, b_row_2))

mask_t4 = np.array([contains_elements(row, arr_b_t4[0], arr_b_t4[1]) for row in arr_a_t4])

print("\nСтроки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B:")
print(arr_a_t4[mask_t4])


Массив А:
[[ 1  4  3]
 [ 9  5  6]
 [12  8  9]
 [ 2  4  7]
 [12  9  8]
 [ 0  6  9]
 [ 1 12  9]
 [ 8  5  9]]

Массив B:
[[ 8  5]
 [ 9 12]]

Строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B:
[[ 9  5  6]
 [12  8  9]
 [12  9  8]
 [ 8  5  9]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [25]:
arr_t5 = np.array([
    [0, 0, 0],
    [3, 7, 9],
    [3, 5, 2],
    [4, 4, 4],
    [4, 2, 6],
    [6, 7, 8],
    [1, 6, 7],
    [5, 3, 1],
    [1, 1, 1],
    [6, 2, 6]
])

print("Исходный массив:")
print(arr_t5)

def are_row_elems_equal(row: np.array) -> bool:
    return np.all(row == row[0])

mask_t5 = np.array([not are_row_elems_equal(a_row) for a_row in arr_t5])

print("Конечный массив:")
print(arr_t5[mask_t5])

Исходный массив:
[[0 0 0]
 [3 7 9]
 [3 5 2]
 [4 4 4]
 [4 2 6]
 [6 7 8]
 [1 6 7]
 [5 3 1]
 [1 1 1]
 [6 2 6]]
Конечный массив:
[[3 7 9]
 [3 5 2]
 [4 2 6]
 [6 7 8]
 [1 6 7]
 [5 3 1]
 [6 2 6]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [26]:
arr_t6 = np.array([
    [4, 4, 4],
    [3, 7, 9],
    [3, 5, 2],
    [4, 4, 4],
    [4, 4, 4],
    [6, 2, 6],
    [1, 6, 7],
    [5, 3, 1],
    [1, 1, 1],
    [6, 2, 6]
])

print("Исходный массив:")
print(arr_t6)

print("Конечный массив:")
print(np.unique(arr_t6, axis=0))

Исходный массив:
[[4 4 4]
 [3 7 9]
 [3 5 2]
 [4 4 4]
 [4 4 4]
 [6 2 6]
 [1 6 7]
 [5 3 1]
 [1 1 1]
 [6 2 6]]
Конечный массив:
[[1 1 1]
 [1 6 7]
 [3 5 2]
 [3 7 9]
 [4 4 4]
 [5 3 1]
 [6 2 6]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [27]:
# Python
arr_t1_p = [
    [0, 0, 1, 9, 8],
    [2, 4, 2, 6, 1],
    [3, 0, 0, 1, 2],
    [4, 4, 4, 25, 6]
]
print("Python")
print("Матрица:")
for row in arr_t1_p:
    print(row)
    
rows_t1_p = len(arr_t1_p)
cols_t1_p = len(arr_t1_p[0]) if rows_t1_p > 0 else 0

dim_size_t1_p = min(rows_t1_p, cols_t1_p)

product_t1_p = 1

for i in range(dim_size_t1_p):
    if arr_t1_p[i][i] != 0:
        product_t1_p *= arr_t1_p[i][i]

print(f"Результат: {product_t1_p}")

Python
Матрица:
[0, 0, 1, 9, 8]
[2, 4, 2, 6, 1]
[3, 0, 0, 1, 2]
[4, 4, 4, 25, 6]
Результат: 100


In [28]:
# NumPy
arr_t1_np = np.array([
    [0, 0, 1, 9, 8],
    [2, 4, 2, 6, 1],
    [3, 0, 0, 1, 2],
    [4, 4, 4, 25, 6]
])

print("NumPy")
print("Матрица:")
print(arr_t1_np)

diag_t1_np = np.diagonal(arr_t1_np)

nonzero_diag_t1_np = diag_t1_np[diag_t1_np != 0]
product_t1_np = np.prod(nonzero_diag_t1_np)

print(f"Результат: {product_t1_np}")

NumPy
Матрица:
[[ 0  0  1  9  8]
 [ 2  4  2  6  1]
 [ 3  0  0  1  2]
 [ 4  4  4 25  6]]
Результат: 100


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [29]:
#Python

x_t2_p = [1,3,3,3,5,5]
y_t2_p = [3,1,5,3,3,5]
z_t2_p = [3,3,3,3,3,3]

print("Python")
print(f"Х: {x_t2_p}")
print(f"Y: {y_t2_p}")
print(f"Z: {z_t2_p}")

print(f"Результат X и Y: {Counter(x_t2_p) == Counter(y_t2_p)}")
print(f"Результат X и Z: {Counter(x_t2_p) == Counter(z_t2_p)}")
print(f"Результат Y и Z: {Counter(y_t2_p) == Counter(z_t2_p)}")

Python
Х: [1, 3, 3, 3, 5, 5]
Y: [3, 1, 5, 3, 3, 5]
Z: [3, 3, 3, 3, 3, 3]
Результат X и Y: True
Результат X и Z: False
Результат Y и Z: False


In [30]:
#NumPy
x_t2_np = np.array([1,3,3,3,5,5])
y_t2_np = np.array([3,1,5,3,3,5])
z_t2_np = np.array([1,5,3,3,3,3])

print("NumPy")
print(f"Х: {x_t2_np}")
print(f"Y: {y_t2_np}")
print(f"Z: {z_t2_np}")

print(f"Результат X и Y: {np.array_equal(np.unique(x_t2_np, return_counts=True), np.unique(y_t2_np, return_counts=True))}")
print(f"Результат X и Z: {np.array_equal(np.unique(x_t2_np, return_counts=True), np.unique(z_t2_np, return_counts=True))}")
print(f"Результат Y и Z: {np.array_equal(np.unique(y_t2_np, return_counts=True), np.unique(z_t2_np, return_counts=True))}")

NumPy
Х: [1 3 3 3 5 5]
Y: [3 1 5 3 3 5]
Z: [1 5 3 3 3 3]
Результат X и Y: True
Результат X и Z: False
Результат Y и Z: False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [31]:
# Python
arr_t3_p = [6, 2, 0, 3, 0, 0, 5, 7, 0]

print("Python")
print("Вектор:")
print(arr_t3_p)

max_val_t3_p = None

for i in range(1, len(arr_t3_p)):
    if arr_t3_p[i-1] == 0:
        if max_val_t3_p is None or arr_t3_p[i] > max_val_t3_p:
            max_val_t3_p = arr_t3_p[i]

print(f"Результат: {max_val_t3_p}") 

Python
Вектор:
[6, 2, 0, 3, 0, 0, 5, 7, 0]
Результат: 5


In [32]:
# NumPy
arr_t3_np = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

print("NumPy")
print("Вектор:")
print(arr_t3_np)

zero_idxs = np.where(arr_t3_np == 0)[0]
if np.max(zero_idxs) == arr_t3_np.size - 1:
    zero_idxs = np.delete(zero_idxs, zero_idxs.argmax())
    
print(f"Результат: {np.max(arr_t3_np[zero_idxs+1])}")

NumPy
Вектор:
[6 2 0 3 0 0 5 7 0]
Результат: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [33]:
# Python
arr_t4_p = [2, 2, 2, 3, 3, 3, 5, 2, 2, 10, 5, 5, 5, 3, 3, 3, 10]

print("Python")
print("Вектор:")
print(arr_t4_p)

# Кодировка длин серий
values_t4_p, counts_t4_p = [], []

if arr_t4_p:  # Проверяем, что список не пуст
    current_value_t4_p = arr_t4_p[0]
    count_t4_p = 1

    for i in range(1, len(arr_t4_p)):
        if arr_t4_p[i] == current_value_t4_p:
            count_t4_p += 1
        else:
            values_t4_p.append(current_value_t4_p)
            counts_t4_p.append(count_t4_p)
            current_value_t4_p = arr_t4_p[i]
            count_t4_p = 1
            
    # Добавляем последний элемент
    values_t4_p.append(current_value_t4_p)
    counts_t4_p.append(count_t4_p)

print(f"Значения: {values_t4_p}")
print(f"Повторы: {counts_t4_p}")


Python
Вектор:
[2, 2, 2, 3, 3, 3, 5, 2, 2, 10, 5, 5, 5, 3, 3, 3, 10]
Значения: [2, 3, 5, 2, 10, 5, 3, 10]
Повторы: [3, 3, 1, 2, 1, 3, 3, 1]


In [34]:
# NumPy
arr_t4_np = np.array([2, 2, 2, 3, 3, 3, 5, 2, 2, 10, 5, 5, 5, 3, 3, 3, 10])

print("NumPy")
print("Вектор:")
print(arr_t4_np)

changes_t4_np = np.diff(arr_t4_np, prepend=arr_t4_np[0] - 1)
series_starts_t4_np = np.where(changes_t4_np != 0)[0]

values_t4_np = arr_t4_np[series_starts_t4_np]
counts_t4_np = np.diff(np.append(series_starts_t4_np, len(arr_t4_np)))

print(f"Значения: {values_t4_np}")
print(f"Повторы: {counts_t4_np}")

NumPy
Вектор:
[ 2  2  2  3  3  3  5  2  2 10  5  5  5  3  3  3 10]
Значения: [ 2  3  5  2 10  5  3 10]
Повторы: [3 3 1 2 1 3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [35]:
# Python

x_t5_p = [[0, -1, 3], [9, -8, 0], [1, -1, 34], [45, -2, 6], [9, -4, -7]]
y_t5_p = [[16, 9, 5], [26, -26, 13], [4, 4, 4], [0, 0, 37], [77, 5, 2]]

print("Python")
print(f"X: {x_t5_p}")
print(f"Y: {y_t5_p}")

def euclidean_distance_p(x_objects, y_objects):
    distances = []
    for x in x_objects:
        row = []
        for y in y_objects:
            dist = sum((xi-yi) ** 2 for xi, yi in zip(x,y)) ** 0.5
            row.append(dist)
        distances.append(row)
    return distances

print(f"Матрица евклидовых расстояний: {euclidean_distance_p(x_t5_p, y_t5_p)}")
print(f"Время выполнения 100000 повторений: {timeit.timeit(lambda: euclidean_distance_p(x_t5_p, y_t5_p), number= 100000)}")


Python
X: [[0, -1, 3], [9, -8, 0], [1, -1, 34], [45, -2, 6], [9, -4, -7]]
Y: [[16, 9, 5], [26, -26, 13], [4, 4, 4], [0, 0, 37], [77, 5, 2]]
Матрица евклидовых расстояний: [[18.973665961010276, 37.429934544425805, 6.48074069840786, 34.0147027033899, 77.23988606931007], [19.05255888325765, 27.964262908219126, 13.601470508735444, 38.91015291668744, 69.26037828369117], [34.14674215792775, 41.12177038990418, 30.56141357987225, 3.3166247903554, 82.68010643437755], [31.0322412983658, 31.400636936215164, 41.48493702538308, 54.680892457969264, 33.0], [19.026297590440446, 34.249087579087416, 14.491376746189438, 45.088801270381985, 69.18092222571191]]
Время выполнения 100000 повторений: 2.0737745410006028


In [36]:
# NumPy

x_t5_np = np.array([[0, -1, 3], [9, -8, 0], [1, -1, 34], [45, -2, 6], [9, -4, -7]])
y_t5_np = np.array([[16, 9, 5], [26, -26, 13], [4, 4, 4], [0, 0, 37], [77, 5, 2]])

print("NumPy")
print(f"X:")
print(x_t5_np)
print(f"Y:")
print(y_t5_np)

def euclidean_distance_np(x_objects, y_objects):
    diff = x_objects[:, np.newaxis, :] - y_objects
    return np.sqrt(np.sum(diff**2, axis=2))

print(f"Матрица евклидовых расстояний:\n {euclidean_distance_np(x_t5_np, y_t5_np)}")
print(f"Время выполнения 100000 повторений: {timeit.timeit(lambda: euclidean_distance_np(x_t5_np, y_t5_np), number= 100000)}")


NumPy
X:
[[ 0 -1  3]
 [ 9 -8  0]
 [ 1 -1 34]
 [45 -2  6]
 [ 9 -4 -7]]
Y:
[[ 16   9   5]
 [ 26 -26  13]
 [  4   4   4]
 [  0   0  37]
 [ 77   5   2]]
Матрица евклидовых расстояний:
 [[18.97366596 37.42993454  6.4807407  34.0147027  77.23988607]
 [19.05255888 27.96426291 13.60147051 38.91015292 69.26037828]
 [34.14674216 41.12177039 30.56141358  3.31662479 82.68010643]
 [31.0322413  31.40063694 41.48493703 54.68089246 33.        ]
 [19.02629759 34.24908758 14.49137675 45.08880127 69.18092223]]
Время выполнения 100000 повторений: 0.6341639999882318


In [37]:
#SciPy
from scipy.spatial.distance import cdist

x_t5_sp = [[0, -1, 3], [9, -8, 0], [1, -1, 34], [45, -2, 6], [9, -4, -7]]
y_t5_sp = [[16, 9, 5], [26, -26, 13], [4, 4, 4], [0, 0, 37], [77, 5, 2]]

print("SciPy")
print(f"Объеты выборки X: {x_t5_sp}")
print(f"Объекты выборки Y: {y_t5_sp}")

def euclidean_distance_sp(x_objects, y_objects):
    return cdist(x_objects, y_objects, 'euclidean')

print(f"Матрица евклидовых расстояний:\n {euclidean_distance_sp(x_t5_sp, y_t5_sp)}")
print(f"Время выполнения 100000 повторений: {timeit.timeit(lambda: euclidean_distance_sp(x_t5_sp, y_t5_sp), number= 100000)}")

SciPy
Объеты выборки X: [[0, -1, 3], [9, -8, 0], [1, -1, 34], [45, -2, 6], [9, -4, -7]]
Объекты выборки Y: [[16, 9, 5], [26, -26, 13], [4, 4, 4], [0, 0, 37], [77, 5, 2]]
Матрица евклидовых расстояний:
 [[18.97366596 37.42993454  6.4807407  34.0147027  77.23988607]
 [19.05255888 27.96426291 13.60147051 38.91015292 69.26037828]
 [34.14674216 41.12177039 30.56141358  3.31662479 82.68010643]
 [31.0322413  31.40063694 41.48493703 54.68089246 33.        ]
 [19.02629759 34.24908758 14.49137675 45.08880127 69.18092223]]
Время выполнения 100000 повторений: 0.6952378339774441


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [38]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [39]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [40]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [41]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [42]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [43]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [44]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [45]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [46]:
# your code